"""Tests for the plan Executor (`app.agent.executor`).

Covers:

- Task 13.2 / Property 9: every executed step emits a well-formed lifecycle. For
  any generated plan executed with arbitrary per-step tool success/failure, each
  executed step emits a ``step_started`` event followed by exactly one terminal
  event (``step_completed`` XOR ``step_failed``); its final status is ``done`` or
  ``failed`` accordingly; and a failed step never halts execution of steps whose
  dependencies are all ``done`` (Req 3.1, 3.3, 3.4).
- Task 13.3 (unit): best-effort degradation — when a bookkeeping dependency (the
  event bus's ``publish`` or the structured logger's ``decision``) raises, the
  run does not crash and every executed step still receives a terminal status
  (Req 3.5).

The Property 9 test drives a **scripted fake tool registry** whose per-tool
success/failure is generated by Hypothesis, and inspects the events buffered on
the :class:`~app.models.schemas.RunState` replay buffer (populated by the real
:class:`~app.core.event_bus.EventBus`). Property tests use Hypothesis at a
minimum of 100 iterations. Each generated example is driven through
:func:`asyncio.run` because :meth:`Executor.run` is asynchronous.
"""

from __future__ import annotations

import asyncio
from typing import Any

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from app.agent.executor import Executor
from app.agent.tools import ToolRegistry, ToolResult
from app.core.event_bus import EventBus
from app.models.schemas import (
    Plan,
    PlanStep,
    RunState,
    SSEEventType,
    StepStatus,
)

# ---------------------------------------------------------------------------
# Scripted fake tool registry
# ---------------------------------------------------------------------------


class ScriptedToolRegistry:
    """A fake tool registry whose per-tool outcome is scripted (Req 3.4).

    Each tool name maps to a boolean: ``True`` means a dispatch succeeds and
    returns a :class:`ToolResult`; ``False`` means every dispatch raises. This
    lets a test drive arbitrary per-step success/failure while structurally
    satisfying the interface the :class:`Executor` uses (``names`` + ``dispatch``).

    Attributes:
        outcomes: Mapping of tool name to whether dispatching it succeeds.
        dispatched: Ordered list of the tool names dispatched (for assertions).
    """

    def __init__(self, outcomes: dict[str, bool]) -> None:
        self.outcomes = outcomes
        self.dispatched: list[str] = []

    def names(self) -> list[str]:
        """Return the registered tool names."""

        return list(self.outcomes)

    async def dispatch(self, name: str, **kwargs: Any) -> ToolResult:
        """Return a canned result for a succeeding tool, else raise (Req 3.4)."""

        self.dispatched.append(name)
        if self.outcomes.get(name, False):
            return ToolResult(output=f"output-{name}", summary=f"did {name}")
        raise RuntimeError(f"scripted failure for tool {name!r}")


# ---------------------------------------------------------------------------
# Hypothesis strategies
# ---------------------------------------------------------------------------

_run_ids = st.text(
    alphabet="abcdefghijklmnopqrstuvwxyz0123456789-",
    min_size=1,
    max_size=10,
)


@st.composite
def _scripted_plans(draw: st.DrawFn) -> tuple[Plan, dict[str, bool]]:
    """Draw a schema-valid plan plus a per-step tool success map.

    Each step ``i`` (1-based) is given the task name ``tool_{i}`` (so the
    executor routes it directly to that registered tool) and a random subset of
    strictly-earlier steps as its dependencies. The returned outcome map keys the
    per-step tool name to whether its dispatch should succeed.
    """

    n = draw(st.integers(min_value=2, max_value=5))
    steps: list[PlanStep] = []
    outcomes: dict[str, bool] = {}
    for i in range(1, n + 1):
        if i > 1:
            depends_on = draw(
                st.lists(
                    st.integers(min_value=1, max_value=i - 1),
                    unique=True,
                    max_size=i - 1,
                )
            )
        else:
            depends_on = []
        tool_name = f"tool_{i}"
        outcomes[tool_name] = draw(st.booleans())
        steps.append(
            PlanStep(
                step=i,
                task=tool_name,
                description=f"description for step {i}",
                expected_output=f"output {i}",
                depends_on=sorted(depends_on),
            )
        )
    return Plan(steps=steps), outcomes


def _expected_execution(
    plan: Plan, outcomes: dict[str, bool]
) -> tuple[set[int], set[int]]:
    """Compute the expected executed/done step sets for a scripted run.

    Mirrors the executor's single ascending pass: a step is *executed* when every
    dependency ended ``done``; an executed step ends ``done`` when its scripted
    tool succeeds, otherwise ``failed``.

    Returns:
        A ``(executed, done)`` tuple of step numbers.
    """

    done: set[int] = set()
    executed: set[int] = set()
    for step in sorted(plan.steps, key=lambda s: s.step):
        if all(dep in done for dep in step.depends_on):
            executed.add(step.step)
            if outcomes[f"tool_{step.step}"]:
                done.add(step.step)
    return executed, done


def _new_run_state(run_id: str, plan: Plan) -> RunState:
    """Build a :class:`RunState` carrying ``plan`` for execution."""

    state = RunState(run_id=run_id, request="do the thing", client_ip="127.0.0.1")
    state.plan = plan
    return state


# ---------------------------------------------------------------------------
# Task 13.2 / Property 9
# ---------------------------------------------------------------------------


# Feature: autonomous-agent-service, Property 9: Every executed step emits a well-formed lifecycle
@pytest.mark.property
@settings(max_examples=100, deadline=None)
@given(run_id=_run_ids, data=_scripted_plans())
def test_property_9_step_lifecycle_and_failure_continuation(
    run_id: str, data: tuple[Plan, dict[str, bool]]
) -> None:
    """Property 9: each executed step emits a well-formed lifecycle.

    **Validates: Requirements 3.1, 3.3, 3.4**

    For any generated plan executed with arbitrary per-step tool success/failure:
    each executed step emits a ``step_started`` event followed by exactly one
    terminal event (``step_completed`` XOR ``step_failed``); its final status is
    ``done`` or ``failed`` accordingly; steps whose dependencies never complete
    are left ``pending``; and a failed step never halts execution of steps whose
    dependencies are all ``done``.
    """

    plan, outcomes = data
    expected_executed, expected_done = _expected_execution(plan, outcomes)

    async def _run() -> None:
        registry = ScriptedToolRegistry(outcomes)
        bus = EventBus()
        state = _new_run_state(run_id, plan)
        # ``max_retries=0`` keeps the property fast; retry bounds are covered
        # elsewhere. Lifecycle/continuation behavior is independent of the count.
        executor = Executor(registry, bus, max_retries=0)  # type: ignore[arg-type]

        await executor.run(state)

        events = state.events
        started_steps = [e.step for e in events if e.type is SSEEventType.STEP_STARTED]
        completed_steps = [
            e.step for e in events if e.type is SSEEventType.STEP_COMPLETED
        ]
        failed_steps = [e.step for e in events if e.type is SSEEventType.STEP_FAILED]

        status_by_number = {s.step: s.status for s in plan.steps}

        for step in plan.steps:
            n = step.step
            started_for_n = started_steps.count(n)
            completed_for_n = completed_steps.count(n)
            failed_for_n = failed_steps.count(n)

            if n not in expected_executed:
                # Unsatisfiable dependencies: never executed, left pending.
                assert status_by_number[n] is StepStatus.PENDING
                assert started_for_n == 0
                assert completed_for_n == 0
                assert failed_for_n == 0
                continue

            # Executed: exactly one start and exactly one terminal event.
            assert started_for_n == 1
            assert completed_for_n + failed_for_n == 1

            # step_started precedes its terminal event.
            start_index = next(
                i
                for i, e in enumerate(events)
                if e.type is SSEEventType.STEP_STARTED and e.step == n
            )
            terminal_index = next(
                i
                for i, e in enumerate(events)
                if e.type
                in (SSEEventType.STEP_COMPLETED, SSEEventType.STEP_FAILED)
                and e.step == n
            )
            assert start_index < terminal_index

            if n in expected_done:
                assert status_by_number[n] is StepStatus.DONE
                assert completed_for_n == 1
                assert failed_for_n == 0
            else:
                assert status_by_number[n] is StepStatus.FAILED
                assert failed_for_n == 1
                assert completed_for_n == 0

        # A failed step never halts execution: every dependency-satisfied step is
        # executed even when an earlier independent step failed.
        for step in plan.steps:
            if all(dep in expected_done for dep in step.depends_on):
                assert step.step in expected_executed

    asyncio.run(_run())


# ---------------------------------------------------------------------------
# Task 13.3 unit tests — best-effort degradation (Req 3.5)
# ---------------------------------------------------------------------------


def _success_registry() -> ToolRegistry:
    """Build a real registry whose two tools always succeed."""

    registry = ToolRegistry()

    async def ok_tool(**kwargs: Any) -> ToolResult:
        return ToolResult(output="ok", summary="ok")

    registry.register("tool_1", ok_tool)
    registry.register("tool_2", ok_tool)
    return registry


def _two_step_plan() -> Plan:
    """Build a simple two-step plan routed to always-succeeding tools."""

    return Plan(
        steps=[
            PlanStep(step=1, task="tool_1", description="first", expected_output="a"),
            PlanStep(step=2, task="tool_2", description="second", expected_output="b"),
        ]
    )


class _BrokenBus:
    """An event bus whose ``publish`` always raises (bookkeeping failure)."""

    async def publish(self, event: Any, run_state: Any = None) -> None:
        raise RuntimeError("event bus is down")


class _BrokenLogger:
    """A logger whose ``decision`` always raises (bookkeeping failure)."""

    def decision(self, *args: Any, **kwargs: Any) -> None:
        raise RuntimeError("logger is down")


async def test_run_does_not_crash_when_event_bus_publish_raises() -> None:
    """A failing event bus never crashes the run; steps still terminalize (Req 3.5)."""

    plan = _two_step_plan()
    state = _new_run_state("run-bus", plan)
    executor = Executor(_success_registry(), _BrokenBus())  # type: ignore[arg-type]

    # Must not raise despite every publish failing.
    await executor.run(state)

    assert all(step.status is StepStatus.DONE for step in plan.steps)


async def test_run_does_not_crash_when_logger_decision_raises() -> None:
    """A failing logger never crashes the run; steps still terminalize (Req 3.5)."""

    plan = _two_step_plan()
    state = _new_run_state("run-log", plan)
    executor = Executor(_success_registry(), EventBus(), _BrokenLogger())  # type: ignore[arg-type]

    await executor.run(state)

    assert all(step.status is StepStatus.DONE for step in plan.steps)


async def test_failed_step_still_terminalizes_under_broken_bookkeeping() -> None:
    """Even with broken bookkeeping, a failing tool yields a FAILED status (Req 3.5)."""

    registry = ToolRegistry()

    async def boom(**kwargs: Any) -> ToolResult:
        raise RuntimeError("tool exploded")

    registry.register("tool_1", boom)
    registry.register("tool_2", boom)

    plan = _two_step_plan()
    state = _new_run_state("run-fail", plan)
    # Broken bus + zero retries: the run must still complete with terminal states.
    executor = Executor(registry, _BrokenBus(), _BrokenLogger(), max_retries=0)  # type: ignore[arg-type]

    await executor.run(state)

    assert all(step.status is StepStatus.FAILED for step in plan.steps)
    assert all(step.error for step in plan.steps)
